In [1]:
import warnings

# Ignore all warnings
warnings.filterwarnings("ignore")


# # Reset warnings to default behavior
# warnings.resetwarnings()

In [2]:
# !pip install sqlalchemy pandas

# Python Script to Create Database, Tables and Insert Dummy Data

In [4]:
import pyodbc
import pandas as pd
from faker import Faker
import random

# Connection parameters
server = 'DESKTOP-89C0DB2'
database = 'master'  # Connect to master to check/create new database
driver = '{SQL Server}'
new_db_name = 'LibraryDB'

# Establish connection for database creation
conn_str = f'DRIVER={driver};SERVER={server};DATABASE={database};Trusted_Connection=yes'
conn = pyodbc.connect(conn_str, autocommit=True)
cursor = conn.cursor()

# Create the new database if it doesn't exist
cursor.execute(f"SELECT database_id FROM sys.databases WHERE name = '{new_db_name}'")
if not cursor.fetchone():
    cursor.execute(f"CREATE DATABASE {new_db_name}")
    print(f"Database '{new_db_name}' created.")
conn.close()

# Connect to the new database for table creation and data manipulation
conn_str = f'DRIVER={driver};SERVER={server};DATABASE={new_db_name};Trusted_Connection=yes'
conn = pyodbc.connect(conn_str)
cursor = conn.cursor()

# Create tables
try:
    cursor.execute("""
        CREATE TABLE Authors (
            AuthorID INT PRIMARY KEY IDENTITY(1,1),
            Name NVARCHAR(100),
            Biography NVARCHAR(MAX)
        )
    """)
    cursor.execute("""
        CREATE TABLE Genres (
            GenreID INT PRIMARY KEY IDENTITY(1,1),
            GenreName NVARCHAR(100)
        )
    """)
    cursor.execute("""
        CREATE TABLE Books (
            BookID INT PRIMARY KEY IDENTITY(1,1),
            Title NVARCHAR(100),
            ISBN NVARCHAR(20),
            PublicationYear INT,
            AuthorID INT FOREIGN KEY REFERENCES Authors(AuthorID),
            GenreID INT FOREIGN KEY REFERENCES Genres(GenreID)
        )
    """)
    cursor.execute("""
        CREATE TABLE Members (
            MemberID INT PRIMARY KEY IDENTITY(1,1),
            Name NVARCHAR(100),
            Email NVARCHAR(100),
            MembershipDate DATE
        )
    """)
    cursor.execute("""
        CREATE TABLE Borrowings (
            BorrowingID INT PRIMARY KEY IDENTITY(1,1),
            MemberID INT FOREIGN KEY REFERENCES Members(MemberID),
            BookID INT FOREIGN KEY REFERENCES Books(BookID),
            BorrowDate DATE,
            ReturnDate DATE
        )
    """)
    cursor.execute("""
        CREATE TABLE Publishers (
            PublisherID INT PRIMARY KEY IDENTITY(1,1),
            Name NVARCHAR(100),
            Address NVARCHAR(255)
        )
    """)
    conn.commit()
except pyodbc.Error as e:
    print("Error creating tables: ", e)
    conn.close()
    exit()

# Insert dummy data
n = 10
fake = Faker()

# Insert into Authors and Genres
for _ in range(n):
    cursor.execute("INSERT INTO Authors (Name, Biography) VALUES (?, ?)", fake.name(), fake.text())
    cursor.execute("INSERT INTO Genres (GenreName) VALUES (?)", fake.word())
conn.commit()

# Insert into Books
for _ in range(n):
    cursor.execute("INSERT INTO Books (Title, ISBN, PublicationYear, AuthorID, GenreID) VALUES (?, ?, ?, ?, ?)",
                   fake.catch_phrase(), fake.isbn13(), random.randint(1900, 2023),
                   random.randint(1, n), random.randint(1, n))
conn.commit()

# Insert into Members
for _ in range(n):
    membership_date = fake.date_between(start_date='-5y', end_date='today').strftime("%Y-%m-%d")
    cursor.execute("INSERT INTO Members (Name, Email, MembershipDate) VALUES (?, ?, ?)",
                   fake.name(), fake.email(), membership_date)
conn.commit()

# Prepare valid MemberID and BookID for Borrowings table
cursor.execute("SELECT MemberID FROM Members")
member_ids = [row[0] for row in cursor.fetchall()]
cursor.execute("SELECT BookID FROM Books")
book_ids = [row[0] for row in cursor.fetchall()]

# Insert into Borrowings
for _ in range(n):
    borrow_date = fake.date_this_year().strftime("%Y-%m-%d")
    return_date = fake.date_this_year().strftime("%Y-%m-%d")
    member_id = random.choice(member_ids) if member_ids else 1
    book_id = random.choice(book_ids) if book_ids else 1
    cursor.execute("INSERT INTO Borrowings (MemberID, BookID, BorrowDate, ReturnDate) VALUES (?, ?, ?, ?)",
                   member_id, book_id, borrow_date, return_date)
conn.commit()

# Insert into Publishers
for _ in range(n):
    cursor.execute("INSERT INTO Publishers (Name, Address) VALUES (?, ?)", fake.company(), fake.address())
conn.commit()

# Query and display data using pandas
try:
    df_books = pd.read_sql("SELECT * FROM Books", conn)
    df_members = pd.read_sql("SELECT * FROM Members", conn)
    print("Books Table Data:")
    print(df_books)
    print("\nMembers Table Data:")
    print(df_members)
except pyodbc.Error as e:
    print("Error querying data: ", e)

# Close the cursor and connection
cursor.close()
conn.close()

Database 'LibraryDB' created.
Books Table Data:
   BookID                                       Title               ISBN  \
0       1                  Phased global secured line  978-0-533-15295-7
1       2      Monitored human-resource knowledgebase  978-1-4153-9555-4
2       3      Assimilated incremental infrastructure  978-1-78109-867-7
3       4     De-engineered optimal open architecture  978-0-335-10433-8
4       5                Monitored encompassing frame  978-1-320-70351-2
5       6               Down-sized holistic structure  978-1-4527-8649-0
6       7  Right-sized attitude-oriented secured line  978-0-7326-2138-4
7       8                Diverse neutral service-desk  978-1-104-91882-8
8       9         Switchable content-based definition  978-1-146-99689-1
9      10          Public-key homogeneous methodology  978-1-128-10067-4

   PublicationYear  AuthorID  GenreID
0             1934         6        1
1             1994         2       10
2             1911         2        3
3             2018         3        9
4             1942         6        1
5             2003         3        5
6             1963        10        6
7             1928         7        7
8             1900        10        9
9             2006         8        2

Members Table Data:
   MemberID              Name                     Email MembershipDate
0         1     Suzanne Smith     randall00@example.org     2023-03-22
1         2        Mary Chase    dawnbarber@example.org     2022-12-07
2         3  Kathleen Jimenez     ryanyoung@example.org     2019-05-29
3         4    Matthew Nguyen       james87@example.org     2020-09-08
4         5  Michelle Vasquez  aprilnichols@example.org     2021-06-30
5         6       Miguel Dean     melanie45@example.net     2022-01-01
6         7  Samantha Houston   rossantonio@example.com     2020-11-27
7         8  Kristy Schroeder      denise74@example.org     2022-12-18
8         9      Alexis Perez       becky99@example.org     2019-03-28
9        10   Robert Robinson     lindahall@example.com     2023-08-28

# Python Script to Retrieve Database Metadata

In [5]:
import pyodbc

# Connection parameters
server = 'DESKTOP-89C0DB2'
database = 'LibraryDB'
driver = '{SQL Server}'

# Connect to the database
conn_str = f'DRIVER={driver};SERVER={server};DATABASE={database};Trusted_Connection=yes'
conn = pyodbc.connect(conn_str)
cursor = conn.cursor()

# Get list of tables in the database
cursor.execute("SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE'")
tables = cursor.fetchall()

# Dictionary to hold table metadata
database_metadata = {}

# Iterate over each table and get column details
for table in tables:
    table_name = table[0]
    cursor.execute(f"""
        SELECT 
            COLUMN_NAME, DATA_TYPE 
        FROM 
            INFORMATION_SCHEMA.COLUMNS 
        WHERE 
            TABLE_NAME = '{table_name}'
    """)
    columns = cursor.fetchall()
    
    # Get foreign key relationships for each table
    cursor.execute(f"""
        SELECT 
            fk.name AS FK_name, 
            tp.name AS parent_table,
            cp.name AS parent_column, 
            tr.name AS ref_table, 
            cr.name AS ref_column
        FROM 
            sys.foreign_keys AS fk
        INNER JOIN 
            sys.tables AS tp ON fk.parent_object_id = tp.object_id
        INNER JOIN 
            sys.tables AS tr ON fk.referenced_object_id = tr.object_id
        INNER JOIN 
            sys.foreign_key_columns AS fkc ON fkc.constraint_object_id = fk.object_id
        INNER JOIN 
            sys.columns AS cp ON fkc.parent_column_id = cp.column_id AND fkc.parent_object_id = cp.object_id
        INNER JOIN 
            sys.columns AS cr ON fkc.referenced_column_id = cr.column_id AND fkc.referenced_object_id = cr.object_id
        WHERE 
            tp.name = '{table_name}'
    """)
    relationships = cursor.fetchall()

    # Store table metadata
    database_metadata[table_name] = {
        'columns': columns,
        'relationships': relationships
    }

# Close the cursor and connection
cursor.close()
conn.close()

# Display the database metadata
for table, metadata in database_metadata.items():
    print(f"Table: {table}")
    for column in metadata['columns']:
        print(f"  Column: {column[0]}, Type: {column[1]}")
    for rel in metadata['relationships']:
        print(f"  Relationship: {rel[0]}, Parent Column: {rel[2]}, References: {rel[3]}.{rel[4]}")
    print()

Table: Authors
  Column: AuthorID, Type: int
  Column: Name, Type: nvarchar
  Column: Biography, Type: nvarchar

Table: Genres
  Column: GenreID, Type: int
  Column: GenreName, Type: nvarchar

Table: Books
  Column: BookID, Type: int
  Column: Title, Type: nvarchar
  Column: ISBN, Type: nvarchar
  Column: PublicationYear, Type: int
  Column: AuthorID, Type: int
  Column: GenreID, Type: int
  Relationship: FK__Books__AuthorID__3B75D760, Parent Column: AuthorID, References: Authors.AuthorID
  Relationship: FK__Books__GenreID__3C69FB99, Parent Column: GenreID, References: Genres.GenreID

Table: Members
  Column: MemberID, Type: int
  Column: Name, Type: nvarchar
  Column: Email, Type: nvarchar
  Column: MembershipDate, Type: date

Table: Borrowings
  Column: BorrowingID, Type: int
  Column: MemberID, Type: int
  Column: BookID, Type: int
  Column: BorrowDate, Type: date
  Column: ReturnDate, Type: date
  Relationship: FK__Borrowing__BookI__4222D4EF, Parent Column: BookID, References: Books.BookID
  Relationship: FK__Borrowing__Membe__412EB0B6, Parent Column: MemberID, References: Members.MemberID

Table: Publishers
  Column: PublisherID, Type: int
  Column: Name, Type: nvarchar
  Column: Address, Type: nvarchar